// TEMPORARY DATA

export const departmentData = [
  {
    id: 1,
    department: "Accounting Office",
    category: "Job Order",
    totalEmployees: 3,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 2,
    department: "Assessors Office",
    category: "Job Order",
    totalEmployees: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 3,
    department: "Consultant’s Office",
    category: "Job Order",
    totalEmployees: 4,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 4,
    department: "Contractual 20%",
    category: "Job Order",
    totalEmployees: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 5,
    department: "Dept. of Agriculture",
    category: "Job Order",
    totalEmployees: 13,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 6,
    department: "DSWD (MSWD)",
    category: "Job Order",
    totalEmployees: 5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 7,
    department: "Dumpsite/MENRO",
    category: "Job Order",
    totalEmployees: 24,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 8,
    department: "Engineering Office 1",
    category: "Job Order",
    totalEmployees: 25,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 9,
    department: "Engineering Office 2",
    category: "Job Order",
    totalEmployees: 17,
    dateCreated: new Date().toISOString(),
  },
  {
    id: 10,
    department: "Engineering Office 3",
    category: "Job Order",
    totalEmployees: 23,
    dateCreated: new Date().toISOString(),
  },
];

export const employeeData = [
  {
    id: 1,
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
  },
  {
    id: 2,
    employeeId: "2025010002",
    employee: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
  },
  {
    id: 3,
    employeeId: "2025010003",
    employee: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
  },
];

export const reportData = [
  {
    id: 1,
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    numDays: "15",
    minsLate: "0",
  },
  {
    id: 2,
    employeeId: "2025010002",
    employee: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    numDays: "14.5",
    minsLate: "5",
  },
  {
    id: 3,
    employeeId: "2025010003",
    employee: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    numDays: "14",
    minsLate: "10",
  },
];

export const singleReportData = [
  {
    id: 1,
    date: "01/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 2,
    date: "02/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 3,
    date: "03/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 4,
    date: "04/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 5,
    date: "05/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 6,
    date: "06/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 7,
    date: "07/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 8,
    date: "08/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 9,
    date: "09/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
  {
    id: 10,
    date: "10/02/2025",
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    timeInAM: "08:00 AM",
    timeOutAM: "12:00 PM",
    timeInPM: "01:00 PM",
    timeOutPM: "05:00 PM",
  },
];

export const rateData = [
  {
    id: 1,
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    rate: "Php 300.00",
    type: "Daily",
  },
  {
    id: 2,
    employeeId: "2025010002",
    employee: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    rate: "Php 300.00",
    type: "Daily",
  },
  {
    id: 3,
    employeeId: "2025010003",
    employee: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    rate: "Php 300.00",
    type: "Daily",
  },
];

export const mandDeducData = [
  {
    id: 1,
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    gsisgs: "",
    ec: "",
    gsisps: "",
    phic: "",
    hdmfgs: "",
    hdmfps: "",
    wtax: "",
    sss: "",
  },
  {
    id: 2,
    employeeId: "2025010002",
    employee: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    gsisgs: "",
    ec: "",
    gsisps: "",
    phic: "",
    hdmfgs: "",
    hdmfps: "",
    wtax: "",
    sss: "",
  },
  {
    id: 3,
    employeeId: "2025010003",
    employee: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    gsisgs: "",
    ec: "",
    gsisps: "",
    phic: "",
    hdmfgs: "",
    hdmfps: "",
    wtax: "",
    sss: "",
  },
];

export const loanDeducData = [
  {
    id: 1,
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    mplhdmf: "",
    gfal: "",
    landbank: "",
    cb: "",
    eml: "",
    mplgsis: "",
    tagum: "",
    ucpb: "",
    mpllite: "",
    sb: "",
  },
  {
    id: 2,
    employeeId: "2025010002",
    employee: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    mplhdmf: "",
    gfal: "",
    landbank: "",
    cb: "",
    eml: "",
    mplgsis: "",
    tagum: "",
    ucpb: "",
    mpllite: "",
    sb: "",
  },
  {
    id: 3,
    employeeId: "2025010003",
    employee: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    mplhdmf: "",
    gfal: "",
    landbank: "",
    cb: "",
    eml: "",
    mplgsis: "",
    tagum: "",
    ucpb: "",
    mpllite: "",
    sb: "",
  },
];

export const summaryData = [
  {
    id: 1,
    employeeId: "2025010001",
    employee: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    earnings: "Php 2,400.00",
    deductions: "Php 0.00",
    income: "Php 2,400.00",
  },
  {
    id: 2,
    employeeId: "2025010002",
    employee: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    earnings: "Php 2,400.00",
    deductions: "Php 0.00",
    income: "Php 2,400.00",
  },
  {
    id: 3,
    employeeId: "2025010003",
    employee: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    earnings: "Php 2,400.00",
    deductions: "Php 0.00",
    income: "Php 2,400.00",
  },
];

export const singleSummaryData = [
  {
    id: 11,
    date: "01/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 12,
    date: "02/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 13,
    date: "03/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 14,
    date: "04/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 15,
    date: "05/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 16,
    date: "06/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 17,
    date: "07/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 18,
    date: "08/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 19,
    date: "09/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 20,
    date: "10/02/2025",
    employee: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
];