// TEMPORARY DATA

export const departmentData = [
  {
    id: 1,
    departmentId: "001",
    deptName: "Accounting Office",
    category: "Job Order",
    totalEmp: "5",
    dateCreated: "10/2/2025",
  },
  {
    id: 2,
    departmentId: "002",
    deptName: "Assessor's Office",
    category: "Job Order",
    totalEmp: "10",
    dateCreated: "10/2/2025",
  },
  {
    id: 3,
    departmentId: "003",
    deptName: "Consultant's Office",
    category: "Job Order",
    totalEmp: "15",
    dateCreated: "10/2/2025",
  },
  {
    id: 4,
    departmentId: "004",
    deptName: "Contractual 20%",
    category: "Job Order",
    totalEmp: "20",
    dateCreated: "10/2/2025",
  },
  {
    id: 5,
    departmentId: "005",
    deptName: "Department of Agriculture",
    category: "Job Order",
    totalEmp: "25",
    dateCreated: "10/2/2025",
  },
  {
    id: 6,
    departmentId: "006",
    deptName: "DSWD (MSWD)",
    category: "Job Order",
    totalEmp: "30",
    dateCreated: "10/2/2025",
  },
  {
    id: 7,
    departmentId: "007",
    deptName: "Dumpsite (MENRO)",
    category: "Job Order",
    totalEmp: "35",
    dateCreated: "10/2/2025",
  },
  {
    id: 8,
    departmentId: "008",
    deptName: "Engineering Office 1",
    category: "Job Order",
    totalEmp: "40",
    dateCreated: "10/2/2025",
  },
  {
    id: 9,
    departmentId: "009",
    deptName: "Engineering Office 2",
    category: "Job Order",
    totalEmp: "45",
    dateCreated: "10/2/2025",
  },
  {
    id: 10,
    departmentId: "010",
    deptName: "Engineering Office 3",
    category: "Job Order",
    totalEmp: "50",
    dateCreated: "10/2/2025",
  },
];

export const employeeData = [
  {
    id: 1,
    employeeId: "2025010001",
    name: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
  },
  {
    id: 2,
    employeeId: "2025010001",
    name: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
  },
  {
    id: 3,
    employeeId: "2025010001",
    name: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
  },
];

export const reportData = [
  {
    id: 1,
    employeeId: "2025010001",
    name: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    numDays: "15",
    minsLate: "0",
  },
  {
    id: 2,
    employeeId: "2025010001",
    name: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    numDays: "14.5",
    minsLate: "5",
  },
  {
    id: 3,
    employeeId: "2025010001",
    name: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    numDays: "14",
    minsLate: "10",
  },
];

export const indivReportData = [
  {
    id: 1,
    date: "01/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 2,
    date: "02/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 3,
    date: "03/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 4,
    date: "04/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 5,
    date: "05/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 6,
    date: "06/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 7,
    date: "07/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 8,
    date: "08/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 9,
    date: "09/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
  {
    id: 10,
    date: "10/02/2025",
    name: "CAILING, CHRISTY",
    timeinam: "08:00 AM",
    timeoutam: "12:00 PM",
    timeinpm: "01:00 PM",
    timeoutpm: "05:00 PM",
  },
];

export const rateData = [
  {
    id: 1,
    employeeId: "2025010001",
    name: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    rate: "Php 300.00",
    type: "Daily",
  },
  {
    id: 2,
    employeeId: "2025010001",
    name: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    rate: "Php 300.00",
    type: "Daily",
  },
  {
    id: 3,
    employeeId: "2025010001",
    name: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    rate: "Php 300.00",
    type: "Daily",
  },
];

export const mandDeducData = [
  {
    id: 1,
    name: "CAILING, CHRISTY",
    department: "Accounting Office",
    gsisgs: "",
    ec: "",
    gsisps: "",
    phic: "",
    hdmfgs: "",
    hdmfps: "",
    wtax: "",
    sss: "",
  },
  {
    id: 2,
    name: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    gsisgs: "",
    ec: "",
    gsisps: "",
    phic: "",
    hdmfgs: "",
    hdmfps: "",
    wtax: "",
    sss: "",
  },
  {
    id: 3,
    name: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    gsisgs: "",
    ec: "",
    gsisps: "",
    phic: "",
    hdmfgs: "",
    hdmfps: "",
    wtax: "",
    sss: "",
  },
];

export const loanDeducData = [
  {
    id: 1,
    name: "CAILING, CHRISTY",
    department: "Accounting Office",
    mplhdmf: "",
    gfal: "",
    landbank: "",
    cb: "",
    eml: "",
    mplgsis: "",
    tagum: "",
    ucpb: "",
    mpllite: "",
    sb: "",
  },
  {
    id: 2,
    name: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    mplhdmf: "",
    gfal: "",
    landbank: "",
    cb: "",
    eml: "",
    mplgsis: "",
    tagum: "",
    ucpb: "",
    mpllite: "",
    sb: "",
  },
  {
    id: 3,
    name: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    mplhdmf: "",
    gfal: "",
    landbank: "",
    cb: "",
    eml: "",
    mplgsis: "",
    tagum: "",
    ucpb: "",
    mpllite: "",
    sb: "",
  },
];

export const summaryData = [
  {
    id: 1,
    employeeId: "2025010001",
    name: "CAILING, CHRISTY",
    department: "Accounting Office",
    category: "Job Order",
    earnings: "Php 2,400.00",
    deductions: "Php 0.00",
    income: "Php 2,400.00",
  },
  {
    id: 2,
    employeeId: "2025010001",
    name: "CABELTO, MICHELLE ANN",
    department: "Accounting Office",
    category: "Job Order",
    earnings: "Php 2,400.00",
    deductions: "Php 0.00",
    income: "Php 2,400.00",
  },
  {
    id: 3,
    employeeId: "2025010001",
    name: "VALCURZA, MA. THERESA",
    department: "Accounting Office",
    category: "Job Order",
    earnings: "Php 2,400.00",
    deductions: "Php 0.00",
    income: "Php 2,400.00",
  },
];

export const indivSummaryData = [
  {
    id: 1,
    date: "01/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 2,
    date: "02/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 3,
    date: "03/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 4,
    date: "04/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 5,
    date: "05/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 6,
    date: "06/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 7,
    date: "07/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 8,
    date: "08/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 9,
    date: "09/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
  {
    id: 10,
    date: "10/02/2025",
    name: "CAILING, CHRISTY",
    salary: "Php 300.00",
    deductions: "Php 0.00",
    earnings: "Php 300.00",
  },
];